Makefile
azure-pipelines.yml

* remove unnessary -runtime binary
* simplify xbuild-all target
* use named dependencies instead of get-deps
* run xbuild-all during PRs

Standardize makefile

---

.gitignore
examples/azure-aks/cnab/app/run
examples/azure-aks/cnab/app/terraform/aks.tf
examples/azure-aks/cnab/app/terraform/main.tf
examples/azure-aks/cnab/app/terraform/output.tf
examples/azure-aks/cnab/app/terraform/params.tf
examples/azure-aks/porter.yaml
pkg/terraform/helpers.go
pkg/terraform/helpers_test.go
pkg/terraform/init.go
pkg/terraform/init_test.go
pkg/terraform/install.go
pkg/terraform/install_test.go
pkg/terraform/status.go
pkg/terraform/uninstall.go
pkg/terraform/upgrade.go
pkg/terraform/upgrade_test.go

This PR adds the ability to use a backend with terraform.  An example bundle has been added utilizing this functionality. 
TODO:
Closes https://github.com/deislabs/porter-terraform/issues/7
Closes https://github.com/deislabs/porter-terraform/issues/4

feat(*): add remote backend support; add example

---

examples/azure-aks/porter.yaml
examples/azure-keyvault/porter.yaml
examples/basic-tf-example/porter.yaml
pkg/terraform/install.go
pkg/terraform/install_test.go
pkg/terraform/testdata/install-input.yaml
pkg/terraform/testdata/invoke-input.yaml
pkg/terraform/testdata/uninstall-input.yaml
pkg/terraform/testdata/upgrade-input.yaml
pkg/terraform/uninstall.go
pkg/terraform/uninstall_test.go
pkg/terraform/upgrade.go
pkg/terraform/upgrade_test.go

Bundles cannot run in an interactive prompt so we need to always run commands that do not trigger terraform to wait for user input. This deprecates the autoApprove field on all actions and always sets -auto-approve flag on terraform commands.
Once people have had a chance to stop setting the autoApprove field in their porter.yaml, we can update the mixin in a later release to remove the field entirely.
Closes #21 
I have tested this against Jeremy's do-porter demo.

Default approve

---

pkg/terraform/build.go
pkg/terraform/build_test.go

Runs `terraform init --backend=false` from the terraform working directory on mixin build, thereby fetching provider plugins at build-time.
Terraform will still be re-init-ed at runtime for all bundle actions in order to set up/using remote backends.  If done so at build-time, credentials and install-specific logic would be embedded in the base invocation image, which we don't wish to enable.
Closes https://github.com/deislabs/porter-terraform/issues/6

feat(build.go): run terraform init (sans backend setup) on build

---

examples/azure-aks/porter.yaml
examples/azure-keyvault/porter.yaml
examples/basic-tf-example/porter.yaml

Updates example manifests to simplify (only provide `tag` now that `invocationImage` naming can be auto-inferred) and to fix per porter conventions (no `destination` object in a `parameter` definition).

ref(examples): update example manifests

---

README.md
pkg/terraform/build.go
pkg/terraform/build_test.go
pkg/terraform/terraform.go
pkg/terraform/testdata/build-input-with-version.yaml

Using https://github.com/deislabs/porter-helm/pull/64, I've added the ability to change the version of Terraform that the mixin uses.
Fixes #41

build: Add ability to set version

---

Makefile
scripts/test/test-cli.sh

* updates the cli test per updated Porter CLI commands
* creates the bin dir if necessary when downloading the porter CLI (needed if `make clean test-cli` is invoked, for example)

fix(test-cli): fix test-cli script per porter usage

---

build/brigade.js
build/brigade.json

Updates Brigade CI per best practices/utilities; adds issue comment support.
I forgot we'd already switched to only running the Azure DevOps pipeline for this project.  Wanted to update the Brigade CI here regardless, just in case we dust it off in the future.
Tested locally via re-running some recent GH event webhooks.
Closes https://github.com/deislabs/porter-terraform/issues/43

ref(build): update Brigade CI

---

README.md
examples/basic-tf-example/porter.yaml
examples/basic-tf-example/terraform/main.tf
examples/basic-tf-example/terraform/outputs.tf
examples/basic-tf-example/terraform/variables.tf

* Updates the README with a sections/examples around patterns for tracking Terraform state
* Updates the "basic" terraform example to serve as an example harnessing Porter to track state
This PR should probably wait until Porter's forthcoming v0.28.0 release as it relies on unreleased/canary features.
~~(Note: CI needs https://github.com/deislabs/porter-terraform/pull/47 to pass)~~

docs(*): update README around state; update basic example

---

pkg/terraform/terraform.go
scripts/test/test-cli.sh

* Removes the trailing newline from the output value returned from `terraform output <output name>` prior to bubbling up
Fixes https://github.com/deislabs/porter-terraform/issues/20
Note: Although the `--json` format flag on `terraform output` looks handy (as noted in https://github.com/deislabs/porter-terraform/issues/20#issuecomment-663593598) it appears the terraform CLI appends the newline character in this case as well -- and we'd have the extra task of removing the wrapping double quotes.  Hence, I went the simpler route and stuck with the default format.

fix(terraform.go): remove trailing newline from output value

---

examples/basic-tf-example/porter.yaml
pkg/terraform/install.go
pkg/terraform/invoke.go
pkg/terraform/uninstall.go

* Adds logic to surround a given `-var` value with single quotes, to allow for vars with spaces, etc. 
Used the examples/guidelines from Terraform via https://www.terraform.io/docs/configuration/variables.html#variables-on-the-command-line
Noticed that the example bundle was failing as the `myvar` default value of `"porter rocks!"` was getting split when running the command:
```
...
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to …
```

fix(*): quote -var value to allow for spaces, etc.

---

README.md

I suggest to separate `build` and `install` Makefile targets to reinforce the fact that the mixin could be installed in the porter distribution (pointed by PORTER_HOME environment variable).

Separate Makefile install target

---

Makefile
build/testdata/bundles/terraform/porter.yaml
examples/azure-aks/porter.yaml
examples/azure-keyvault/porter.yaml
examples/basic-tf-example/porter.yaml
scripts/test/test-cli.sh

The runtime was moved, it should now be installed to ~/.porter/mixins/MIXIN/runtimes/MIXIN-runtime
Signed-off-by: Carolyn Van Slyck <me@carolynvanslyck.com>

Fix make install

---

Makefile

This prevents canary and latest from being matched, only versions like v1.2.3 should be picked up.

chore(Makefile): fix tag matching

---

README.md
build/testdata/bundles/terraform/terraform/variables.tf
examples/azure-aks/porter.yaml
examples/azure-aks/terraform/main.tf
examples/azure-keyvault/terraform/main.tf
examples/basic-tf-example/porter.yaml
pkg/terraform/build_test.go
pkg/terraform/terraform.go

This PR bumps the default Terraform version to `1.0.4`
fixes #70

Bump default Terraform version to 1.0.4

---

pkg/terraform/action.go
pkg/terraform/schema/schema.json

* Removes the deprecated `autoApprove` field on a terraform mixin step

ref(*): remove deprecated autoApprove field

---

README.md
pkg/terraform/install.go
pkg/terraform/install_test.go
pkg/terraform/testdata/install-input-no-vars-block.yaml

* When install is called with no `vars` block and is running in the default mode of creating a tfvars file, set the generated tfvars file to an empty JSON object rather than the "null" string returned from json.Marshal
i.e., avoids:
```
╷
│ Error: Root value must be object
│
│   on terraform.tfvars.json line 1:
│    1: null
│
│ The root value in a JSON-based configuration must be either a JSON object
│ or a JSON array of objects.
╵
```
Fixes https://github.com/getporter/terraform-mixin/issues/74

fix(install.go): allow for empty var block when generating tfvars file

---

pkg/terraform/build.go
pkg/terraform/build_test.go

When using `terraform-mixin`, Terraform CLI will be downloaded and installed as part of the invocation image. 
The downloaded zip remained in the invocation image until now.
This PR removes the ZIP archive from the image once it has been extracted.
fixes #60

Remove Terraform zip-file once it has been extracted

---

README.md
examples/azure-aks/porter.yaml
examples/azure-keyvault/porter.yaml
pkg/terraform/action.go
pkg/terraform/action_test.go
pkg/terraform/install.go
pkg/terraform/install_test.go
pkg/terraform/schema/schema.json
pkg/terraform/testdata/bad-upgrade-disable-save-var.yaml
pkg/terraform/testdata/install-input-disable-save-vars.yaml
pkg/terraform/testdata/install-input.yaml
pkg/terraform/testdata/invoke-input.yaml
pkg/terraform/testdata/step-input.yaml
pkg/terraform/testdata/upgrade-input.yaml
pkg/terraform/uninstall.go
pkg/terraform/uninstall_test.go
pkg/terraform/upgrade_test.go

* Removes the `input` field from a terraform step
Per https://github.com/getporter/terraform-mixin/issues/72, Porter wouldn't be able to support running a step with `input=true` as Porter's runtime is always in a non-interactive Docker container.
Closes https://github.com/getporter/terraform-mixin/issues/72

ref(*): remove input field

---

README.md

This adds an example for how to use the terraform mixin with the v1 prerelease of porter.

Add example on how to use the v1 state section

---

README.md
pkg/terraform/build.go

Fixes #90.
When we build the bundle we can and should mirror the plugins terraform would use in runtime so that the bundle will be more self sufficient and won't need to access Terraform/Hashicorp endpoints to download things.

Mirror plugins during build

---

build/testdata/bundles/terraform/porter.yaml
build/testdata/bundles/terraform/terraform/outputs.tf
build/testdata/bundles/terraform/terraform/variables.tf
pkg/terraform/terraform.go
scripts/test/test-cli.sh

Signed-off-by: Steven Gettys <s.gettys@f5.com>
Closes #94 
Terraform outputs from porter included escaped html characters for things like connection strings. This is a regression due to switching from -raw to -json. The reason the switch occurred is because -raw only supports number, boolean, and string outputs from terraform.
The mixin will decode all of the json strings and remove the html escapes. This works for complex nested objects like arrays and maps as well as strings

Added json unmarshal for potentially encoded JSON string values

---

go.mod
pkg/terraform/schema/schema.json
pkg/terraform/schema_test.go

Include the mixin declaration in the results of the schema command. This way VS Code displays proper highlighting and autocompletion when setting configuration settings when declaring the mixin, such as a client version.

Include mixin declaration schema

---

pkg/terraform/build.go

1. Since buildkit is now in use with porter v1, most other apt calls have started to use RUN commands with mounts. This does the same in the mixin.
2. Remove some of the wget noise as it downloads the terraform cli

Build using mount cache

---

README.md
pkg/terraform/build.go
pkg/terraform/build_test.go
pkg/terraform/config.go
pkg/terraform/config_test.go
pkg/terraform/terraform.go
pkg/terraform/testdata/build-input-with-config.yaml
pkg/terraform/version.go

This PR sets Azure User Agent environment variable so that the azure terraform provider will be able to pick it up.
Users have options to opt out of it by setting the corresponding config.
related issue: #103

Set azure user agent env for azure provider

---

.github/workflows/terraform-mixin.yml

- Add version tags (v*) as workflow triggers
- Exclude canary and latest tags from triggering workflow
Otherwise a new version won't be release when creaing the release tag. It is a mistake during from the conversion from Azure Pipelines to Github Actions that it wasn't triggering on tags

Add tag triggers for mixin workflow

---

README.md
pkg/terraform/build.go
pkg/terraform/build_test.go
pkg/terraform/testdata/build-input-in-airgapped-env.yaml

This makes it possible to mirror the hashicorp official install host and installing terraform in an environment where the official release host is not reachable.
Moreover, this also adds the ability to provide a provider mirror host from which to install providers when the official regsitry is not reachable.
Fixes #123.

feat(build): support installing terraform or providers in airgapped env

---

pkg/terraform/build.go
pkg/terraform/build_test.go

Without this in the generated dockerfile snippet, the user will have to add this environment variable to their own dockerfile and know the path to where the provider configuration file is written.
Workaround currently is to add this to the dockerfile of the bundle before `# PORTER_MIXINS`:
```Dockerfile
ENV TF_CLI_CONFIG_FILE=${BUNDLE_DIR}/${terraform_workdir}/provider_mirror.tfrc
```
where `${terraform_workdir}` is the working dir as configured in the mixin declaration.
Follow up PR to #125.

fix(build): add env var to point to provider config
